import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { AlertTriangle, CheckCircle2, ChevronDown, ChevronUp, Loader2, Plus, Save } from "lucide-react";
import { SchemePartyNotesButton } from "@/components/admin/SchemePartyNotesButton";
import { Stat } from "./Stat"; import { ProgressRing } from "./ProgressRing"; import { SchemeConfigEditor } from "./SchemeConfigEditor"; import { InvoiceCard } from "./InvoiceCard"; import { InvoiceDialog } from "./InvoiceDialog";
import { MONTH_NAME, SCHEME_LABEL, aggregateRowsByItem, computeAchievementPct, computeFreeReport, defaultConfig, fmt, fyCalendarYear } from "./utils";
import type { Invoice, Row, SchemeKind, SchemeRow, VendorMonth } from "./types";

export function MonthBlock({ vm, fy, savedSchemes, onChange, onSave }: { vm: VendorMonth; fy: number; savedSchemes: SchemeRow[]; onChange: (patch: Partial<VendorMonth>) => void; onSave: () => void | Promise<void>; }) {
 const [open,setOpen]=useState(false),[dialogOpen,setDialogOpen]=useState(false),[saving,setSaving]=useState(false); const [dialogInvoice,setDialogInvoice]=useState<Invoice|null>(null);
 const isCurrent=(()=>{const n=new Date();return n.getFullYear()===fyCalendarYear(fy,vm.month)&&n.getMonth()+1===vm.month})(); useEffect(()=>{if(isCurrent)setOpen(true)},[isCurrent]);
 const invoices:Invoice[]=vm.invoices?.length?vm.invoices:(vm.purchase_rows.length?[{id:"legacy",label:"Invoice 1",rows:vm.purchase_rows}]:[]); const flatRows:Row[]=invoices.flatMap(i=>i.rows);
 const setInvoices=(next:Invoice[])=>onChange({invoices:next,purchase_rows:next.flatMap(i=>i.rows)}); const updateInvoice=(id:string,patch:Partial<Invoice>)=>setInvoices(invoices.map(i=>i.id===id?{...i,...patch}:i));
 const report=useMemo(()=>computeFreeReport({kind:vm.scheme_kind,config:vm.scheme_config},aggregateRowsByItem(flatRows)),[vm.scheme_kind,vm.scheme_config,vm.invoices,vm.purchase_rows]);
 const totalQty=flatRows.reduce((s,r)=>s+(+r.qty||0),0),totalAmount=flatRows.reduce((s,r)=>s+(+r.amountWithTax||0),0),totalMrp=flatRows.reduce((s,r)=>s+(+r.mrp||0)*(+r.qty||0),0); const discount=totalMrp>0?(totalMrp-totalAmount)/totalMrp*100:0;
 const free=report.rep.reduce((s:number,r:any)=>s+(+r.free||0),0),targets=((report as any).targets||[]) as any[]; const completion=computeAchievementPct({kind:vm.scheme_kind,config:vm.scheme_config},aggregateRowsByItem(flatRows)); const label=`${MONTH_NAME[vm.month]} ${fyCalendarYear(fy,vm.month)}`;
 const applySaved=(id:string)=>{const s=savedSchemes.find(x=>x.id===id);if(s)onChange({scheme_kind:s.kind,scheme_config:s.config||defaultConfig(s.kind)})};
 const handleSave=async()=>{if(saving)return;setSaving(true);try{await onSave()}finally{setSaving(false)}};
 return <div className={`rounded-2xl border-2 bg-card shadow-sm ${isCurrent?"border-primary/50":"border-border"}`}>
  <button onClick={()=>setOpen(!open)} className="flex w-full items-center gap-4 px-4 py-3 text-left"><div className="flex h-12 w-12 flex-col items-center justify-center rounded-xl bg-primary/10 text-primary"><span className="text-[9px]">{MONTH_NAME[vm.month]}</span><b className="text-xs">{String(fyCalendarYear(fy,vm.month)).slice(-2)}</b></div><div className="flex-1"><div className="font-display">{label} {isCurrent&&<span className="ml-2 rounded-full bg-primary px-2 py-0.5 text-[10px] text-primary-foreground">CURRENT</span>}</div><div className="text-xs text-muted-foreground">{totalQty} qty · ₹{fmt(totalAmount)} · {discount.toFixed(2)}% base discount · <span className="text-emerald-600">{free} free</span></div></div><b>{completion}%</b>{open?<ChevronUp/>:<ChevronDown/>}</button>
  {open&&<div className="space-y-4 border-t p-4">
   <section className="rounded-xl border bg-background/50 p-4"><div className="mb-2 flex justify-between"><h4 className="text-sm font-semibold">① Scheme configuration</h4>{savedSchemes.length>0&&<Select value="" onValueChange={applySaved}><SelectTrigger className="h-8 w-[200px]"><SelectValue placeholder="Apply template…"/></SelectTrigger><SelectContent>{savedSchemes.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select>}</div><div className="mb-3 max-w-md"><Label className="text-xs">Scheme type</Label><Select value={vm.scheme_kind} onValueChange={v=>onChange({scheme_kind:v as SchemeKind,scheme_config:defaultConfig(v as SchemeKind)})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{(Object.keys(SCHEME_LABEL) as SchemeKind[]).map(k=><SelectItem key={k} value={k}>{SCHEME_LABEL[k]}</SelectItem>)}</SelectContent></Select></div><SchemeConfigEditor scheme={{kind:vm.scheme_kind,config:vm.scheme_config}} onChange={c=>onChange({scheme_config:c})}/></section>
   <section className="rounded-xl border-2 border-dashed p-4"><div className="mb-3 flex flex-wrap justify-between gap-2"><h4 className="font-semibold">② Invoices for {label}</h4><div className="flex gap-3"><Stat label="Invoices" value={String(invoices.length)}/><Stat label="Cost" value={`₹${fmt(totalAmount)}`}/><Stat label="MRP" value={`₹${fmt(totalMrp)}`}/><Stat label="Base Discount" value={`${discount.toFixed(2)}%`} tone={discount>0?"success":undefined}/></div></div><Button size="sm" onClick={()=>{setDialogInvoice({id:crypto.randomUUID(),label:`Invoice ${invoices.length+1}`,rows:[]});setDialogOpen(true)}}><Plus className="h-4 w-4"/> Add Invoice</Button><div className="mt-3 space-y-3">{invoices.map((inv,i)=><InvoiceCard key={inv.id} index={i} invoice={inv} onChange={p=>updateInvoice(inv.id,p)} onRemove={()=>setInvoices(invoices.filter(x=>x.id!==inv.id))} onEdit={()=>{setDialogInvoice(inv);setDialogOpen(true)}}/>)}</div></section>
   <InvoiceDialog open={dialogOpen} invoice={dialogInvoice} onClose={()=>setDialogOpen(false)} onSave={inv=>{const exists=invoices.some(x=>x.id===inv.id);setInvoices(exists?invoices.map(x=>x.id===inv.id?inv:x):[...invoices,inv]);setDialogOpen(false)}}/>
   <section className="rounded-xl border bg-background/50 p-4"><h4 className="mb-3 font-semibold">③ Scheme decision alert</h4>{flatRows.length===0?<p className="text-sm text-muted-foreground">Add an invoice to start live scheme analysis.</p>:<div className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border-2 border-emerald-500/30 bg-emerald-500/5 p-4"><div className="flex gap-3"><ProgressRing pct={completion} size={72}/><div><div className="flex items-center gap-1 text-emerald-700"><CheckCircle2 className="h-4 w-4"/><b>Achieved: {free} free</b></div><div className="mt-1 text-xs text-muted-foreground">Purchase ₹{fmt(totalAmount)} · MRP ₹{fmt(totalMrp)} · base discount {discount.toFixed(2)}%</div></div></div></div><div className="rounded-xl border-2 border-amber-500/40 bg-amber-500/5 p-4"><div className="flex items-center gap-1 text-amber-700"><AlertTriangle className="h-4 w-4"/><b className="text-sm">What to buy next</b></div>{targets.length?<div className="mt-2 space-y-2">{targets.slice(0,4).map((t:any,i:number)=><div key={i} className="rounded-lg border bg-background/70 p-2 text-xs"><b>Buy {fmt(t.gap)} more</b> → {t.reward}<div className="text-muted-foreground">Current {fmt(t.have)} / target {fmt(t.need)}. Complete within this scheme period to unlock the benefit.</div></div>)}</div>:<p className="mt-2 text-xs text-emerald-700">Current available target is achieved. Check the next scheme/slab before placing the next purchase.</p>}</div></div>}</section>
   <div className="flex justify-end gap-2"><SchemePartyNotesButton partyId={vm.party_id}/><Button onClick={handleSave} disabled={saving}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}{saving?"Saving…":`Save ${MONTH_NAME[vm.month]}`}</Button></div>
  </div>}
 </div>;
}
