import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "@/hooks/use-toast";
import { IndianRupee, Loader2, MessageCircle, ReceiptIndianRupee, RefreshCw } from "lucide-react";
import { formatINR } from "@/lib/brand";
import { openWhatsAppApp } from "@/lib/whatsapp";

type Row = { id:string; quotation_id:string|null; bill_no:string|null; customer_name:string|null; place:string|null; phone:string|null; pending_amount:number; original_amount:number|null; source:string|null; closed_at:string|null; updated_at:string };

export default function OrderReceivablesPanel(){
 const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [pay,setPay]=useState<Row|null>(null); const [amount,setAmount]=useState(""); const [method,setMethod]=useState("cash"); const [reference,setReference]=useState(""); const [saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true); const {data,error}=await supabase.from("receivables").select("id,quotation_id,bill_no,customer_name,place,phone,pending_amount,original_amount,source,closed_at,updated_at").eq("source","quotation").is("closed_at",null).gt("pending_amount",0).order("pending_amount",{ascending:false}); if(error) toast({title:"Receivables load failed",description:error.message,variant:"destructive"}); else setRows((data??[]) as Row[]); setLoading(false)};
 useEffect(()=>{load()},[]);
 const total=useMemo(()=>rows.reduce((s,r)=>s+Number(r.pending_amount||0),0),[rows]);
 const receive=async()=>{if(!pay)return; const n=Number(amount); if(!n||n<=0||n>Number(pay.pending_amount)){toast({title:"Enter a valid received amount",variant:"destructive"});return} setSaving(true); const {error}=await supabase.from("receivable_payments").insert({receivable_id:pay.id,quotation_id:pay.quotation_id,amount:n,payment_method:method,reference_no:reference.trim()||null}); setSaving(false); if(error){toast({title:"Payment save failed",description:error.message,variant:"destructive"});return} toast({title:"Amount received",description:`${formatINR(n)} recorded from ${pay.customer_name||"customer"}.`}); setPay(null);setAmount("");setReference("");load()};
 const remind=(r:Row)=>{if(!r.phone)return toast({title:"Customer phone missing",variant:"destructive"}); openWhatsAppApp(r.phone,`Hi ${r.customer_name||""}, this is a reminder from Hitech Furniture & Interiors. Balance to receive for ${r.bill_no||"your order"}: ${formatINR(Number(r.pending_amount||0))}. Thank you.`)};
 return <div className="space-y-3">
  <div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-display text-xl font-semibold">Order Receivables</h2><p className="text-xs text-muted-foreground">Customer → Hitech: balance still to receive after delivery.</p></div><Button size="sm" variant="outline" onClick={load}><RefreshCw className="mr-1 h-4 w-4"/>Refresh</Button></div>
  <div className="grid gap-2 sm:grid-cols-2"><Card><CardContent className="p-3"><p className="text-xs text-muted-foreground">Customers to Collect</p><p className="text-2xl font-bold">{rows.length}</p></CardContent></Card><Card><CardContent className="p-3"><p className="text-xs text-muted-foreground">Total Balance to Receive</p><p className="text-2xl font-bold">{formatINR(total)}</p></CardContent></Card></div>
  {loading?<div className="flex justify-center py-8"><Loader2 className="h-5 w-5 animate-spin"/></div>:rows.length===0?<p className="rounded-lg border p-6 text-center text-sm text-muted-foreground">No delivered-order balance pending.</p>:rows.map(r=><Card key={r.id}><CardContent className="p-3"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-1.5"><Badge>Auto from Order</Badge><span className="font-mono text-xs font-semibold">{r.bill_no}</span></div><p className="mt-1 font-medium">{r.customer_name} <span className="font-normal text-muted-foreground">· {r.place}</span></p>{r.phone&&<p className="text-xs text-muted-foreground">{r.phone}</p>}</div><div className="sm:text-right"><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Balance to Receive</p><p className="font-display text-xl font-bold">{formatINR(Number(r.pending_amount))}</p>{r.original_amount!=null&&<p className="text-[10px] text-muted-foreground">Original {formatINR(Number(r.original_amount))}</p>}</div><div className="flex flex-wrap gap-1.5"><Button size="sm" onClick={()=>{setPay(r);setAmount(String(r.pending_amount))}}><IndianRupee className="mr-1 h-4 w-4"/>Receive Payment</Button>{r.phone&&<Button size="sm" variant="outline" onClick={()=>remind(r)}><MessageCircle className="mr-1 h-4 w-4"/>WhatsApp</Button>}{r.quotation_id&&<Button asChild size="sm" variant="ghost"><Link to={`/admin/quotations/${r.quotation_id}`}><ReceiptIndianRupee className="mr-1 h-4 w-4"/>Order</Link></Button>}</div></div></CardContent></Card>)}
  <Dialog open={!!pay} onOpenChange={o=>!o&&setPay(null)}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Receive from Customer</DialogTitle></DialogHeader>{pay&&<div className="space-y-3"><div className="rounded-lg bg-muted p-3"><p className="font-medium">{pay.customer_name}</p><p className="text-xs text-muted-foreground">Balance: {formatINR(Number(pay.pending_amount))}</p></div><div><Label>Amount received</Label><Input type="number" min="0" max={pay.pending_amount} value={amount} onChange={e=>setAmount(e.target.value)}/></div><div><Label>Payment method</Label><Select value={method} onValueChange={setMethod}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="cash">Cash</SelectItem><SelectItem value="upi">UPI / GPay</SelectItem><SelectItem value="card">Card</SelectItem><SelectItem value="bank">Bank Transfer</SelectItem><SelectItem value="cheque">Cheque</SelectItem><SelectItem value="other">Other</SelectItem></SelectContent></Select></div><div><Label>Reference / note (optional)</Label><Input value={reference} onChange={e=>setReference(e.target.value)} placeholder="UPI ref, receipt no..."/></div></div>}<DialogFooter><Button variant="outline" onClick={()=>setPay(null)}>Cancel</Button><Button onClick={receive} disabled={saving}>{saving&&<Loader2 className="mr-1 h-4 w-4 animate-spin"/>}Save Received</Button></DialogFooter></DialogContent></Dialog>
 </div>
}