import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/hooks/use-toast";
import { CalendarClock, CheckCircle2, IndianRupee, Loader2, MessageCircle, Phone, Plus, RefreshCw } from "lucide-react";
import { openWhatsAppApp } from "@/lib/whatsapp";

const db = supabase as any;
type Row={id:string;bill_no:string|null;customer_name:string|null;email:string|null;place:string|null;phone:string|null;pending_amount:number;original_amount:number|null;next_follow_up_at:string|null;last_follow_up_at:string|null;closed_at:string|null};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n||0);
const dayKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;

export default function ReceivableFollowupCRM(){
 const [searchParams]=useSearchParams();
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[addOpen,setAddOpen]=useState(false),[follow,setFollow]=useState<Row|null>(null),[receive,setReceive]=useState<Row|null>(null),[saving,setSaving]=useState(false),[focusId,setFocusId]=useState<string|null>(null);
 const [name,setName]=useState(""),[email,setEmail]=useState(""),[place,setPlace]=useState(""),[phone,setPhone]=useState(""),[balance,setBalance]=useState(""),[bill,setBill]=useState("");
 const [promiseDate,setPromiseDate]=useState(""),[followNote,setFollowNote]=useState(""),[receiveAmount,setReceiveAmount]=useState("");
 const load=async()=>{setLoading(true);const{data,error}=await db.from("receivables").select("id,bill_no,customer_name,email,place,phone,pending_amount,original_amount,next_follow_up_at,last_follow_up_at,closed_at").eq("source","manual").is("closed_at",null).gt("pending_amount",0).order("next_follow_up_at",{ascending:true,nullsFirst:false});if(error)toast({title:"Receivables load failed",description:error.message,variant:"destructive"});else setRows(data??[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 useEffect(()=>{const followupId=searchParams.get("followup");if(!followupId)return;db.from("receivable_followups").select("receivable_id").eq("id",followupId).maybeSingle().then(({data}:any)=>{if(data?.receivable_id)setFocusId(data.receivable_id)});},[searchParams]);
 useEffect(()=>{if(!focusId||loading)return;const el=document.getElementById(`receivable-${focusId}`);if(el){window.setTimeout(()=>el.scrollIntoView({behavior:"smooth",block:"center"}),150)}},[focusId,loading,rows]);
 const today=dayKey(new Date()); const todayRows=useMemo(()=>rows.filter(r=>r.next_follow_up_at&&dayKey(new Date(r.next_follow_up_at))===today),[rows,today]); const overdue=useMemo(()=>rows.filter(r=>r.next_follow_up_at&&dayKey(new Date(r.next_follow_up_at))<today),[rows,today]);
 const addCustomer=async()=>{const amt=Number(balance);if(!name.trim()||!amt||amt<=0){toast({title:"Customer name and balance are required",variant:"destructive"});return}setSaving(true);const{error}=await db.from("receivables").insert({customer_name:name.trim(),email:email.trim()||null,place:place.trim()||null,phone:phone.replace(/\D/g,"").slice(-10)||null,pending_amount:amt,original_amount:amt,bill_no:bill.trim()||null,source:"manual",raw_text:"Manual receivable CRM entry"});setSaving(false);if(error){toast({title:"Could not add customer",description:error.message,variant:"destructive"});return}toast({title:"Receivable customer added",description:`${name} · ${money(amt)} to receive`});setAddOpen(false);setName("");setEmail("");setPlace("");setPhone("");setBalance("");setBill("");load()};
 const schedule=async()=>{if(!follow||!promiseDate)return;setSaving(true);await db.from("receivable_followups").update({status:"cancelled"}).eq("receivable_id",follow.id).eq("status","pending");const scheduled=new Date(`${promiseDate}T09:00:00+05:30`).toISOString();const{error}=await db.from("receivable_followups").insert({receivable_id:follow.id,scheduled_for:scheduled,note:followNote.trim()||"Customer promised payment on this date"});setSaving(false);if(error){toast({title:"Follow-up save failed",description:error.message,variant:"destructive"});return}toast({title:"Follow-up reminder set",description:`${follow.customer_name} · ${promiseDate}`});setFollow(null);setPromiseDate("");setFollowNote("");load()};
 const contacted=async(r:Row)=>{const{data}=await db.from("receivable_followups").select("id").eq("receivable_id",r.id).eq("status","pending").order("scheduled_for",{ascending:true}).limit(1);if(data?.[0]?.id){await db.from("receivable_followups").update({status:"completed",completed_at:new Date().toISOString(),outcome:"Customer contacted"}).eq("id",data[0].id);toast({title:"Marked contacted",description:"Set a new promise date if customer gave another date."});load()}};
 const recordReceived=async()=>{if(!receive)return;const amt=Number(receiveAmount);if(!amt||amt<=0||amt>Number(receive.pending_amount)){toast({title:"Enter a valid received amount",variant:"destructive"});return}setSaving(true);const{error}=await db.from("receivable_payments").insert({receivable_id:receive.id,amount:amt,payment_method:"cash"});setSaving(false);if(error){toast({title:"Payment save failed",description:error.message,variant:"destructive"});return}toast({title:"Amount received",description:`${money(amt)} recorded`});setReceive(null);setReceiveAmount("");load()};
 const whatsapp=(r:Row)=>{if(!r.phone)return;openWhatsAppApp(r.phone,`Hi ${r.customer_name||""}, reminder from Hitech Furniture & Interiors regarding balance ${money(Number(r.pending_amount))}. Thank you.`)};
 return <div className="space-y-3">
  <div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-display text-xl font-semibold">Receivable Follow-up CRM</h2><p className="text-xs text-muted-foreground">Add customers manually and track the date they promised to pay.</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={load}><RefreshCw className="mr-1 h-4 w-4"/>Refresh</Button><Button size="sm" onClick={()=>setAddOpen(true)}><Plus className="mr-1 h-4 w-4"/>Add Customer</Button></div></div>
  <div className="grid gap-2 sm:grid-cols-3"><Card><CardContent className="p-3"><p className="text-xs text-muted-foreground">Manual Receivables</p><p className="text-2xl font-bold">{rows.length}</p></CardContent></Card><Card><CardContent className="p-3"><p className="text-xs text-muted-foreground">Call Today</p><p className="text-2xl font-bold">{todayRows.length}</p></CardContent></Card><Card><CardContent className="p-3"><p className="text-xs text-muted-foreground">Overdue Follow-ups</p><p className="text-2xl font-bold">{overdue.length}</p></CardContent></Card></div>
  {loading?<div className="flex justify-center py-8"><Loader2 className="h-5 w-5 animate-spin"/></div>:rows.length===0?<p className="rounded-lg border p-6 text-center text-sm text-muted-foreground">No manual receivable customers yet.</p>:rows.map(r=>{const due=r.next_follow_up_at?dayKey(new Date(r.next_follow_up_at)):null;const isToday=due===today,isOver=!!due&&due<today,isFocus=focusId===r.id;return <Card id={`receivable-${r.id}`} key={r.id} className={isFocus?"border-primary ring-2 ring-primary/30":isOver?"border-destructive/40":isToday?"border-amber-500/40":""}><CardContent className="p-3"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-1.5">{isFocus&&<Badge>REMINDER</Badge>}{isToday&&<Badge>CALL TODAY</Badge>}{isOver&&<Badge variant="destructive">OVERDUE</Badge>}{!r.next_follow_up_at&&<Badge variant="secondary">No follow-up date</Badge>}</div><p className="mt-1 font-semibold">{r.customer_name}</p><p className="text-xs text-muted-foreground">{[r.place,r.phone,r.email].filter(Boolean).join(" · ")||"No contact details"}</p>{r.next_follow_up_at&&<p className="mt-1 text-xs"><CalendarClock className="mr-1 inline h-3.5 w-3.5"/>Promised / follow-up: <b>{new Date(r.next_follow_up_at).toLocaleDateString("en-IN")}</b></p>}</div><div className="lg:text-right"><p className="text-[10px] uppercase text-muted-foreground">Balance to Receive</p><p className="font-display text-xl font-bold">{money(Number(r.pending_amount))}</p></div><div className="flex flex-wrap gap-1.5"><Button size="sm" onClick={()=>{setFollow(r);setPromiseDate(r.next_follow_up_at?dayKey(new Date(r.next_follow_up_at)):"")}}><CalendarClock className="mr-1 h-4 w-4"/>Promise Date</Button>{r.next_follow_up_at&&<Button size="sm" variant="outline" onClick={()=>contacted(r)}><CheckCircle2 className="mr-1 h-4 w-4"/>Contacted</Button>}<Button size="sm" variant="outline" onClick={()=>{setReceive(r);setReceiveAmount(String(r.pending_amount))}}><IndianRupee className="mr-1 h-4 w-4"/>Received</Button>{r.phone&&<Button size="icon" variant="outline" onClick={()=>location.href=`tel:+91${r.phone}`}><Phone className="h-4 w-4"/></Button>}{r.phone&&<Button size="icon" variant="outline" onClick={()=>whatsapp(r)}><MessageCircle className="h-4 w-4"/></Button>}</div></div></CardContent></Card>})}
  <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent><DialogHeader><DialogTitle>Add Receivable Customer</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div><Label>Customer name *</Label><Input value={name} onChange={e=>setName(e.target.value)}/></div><div><Label>Balance to receive *</Label><Input type="number" value={balance} onChange={e=>setBalance(e.target.value)}/></div><div><Label>Phone</Label><Input value={phone} onChange={e=>setPhone(e.target.value)}/></div><div><Label>Email</Label><Input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div><Label>Place</Label><Input value={place} onChange={e=>setPlace(e.target.value)}/></div><div><Label>Bill / reference no.</Label><Input value={bill} onChange={e=>setBill(e.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setAddOpen(false)}>Cancel</Button><Button onClick={addCustomer} disabled={saving}>Add Customer</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={!!follow} onOpenChange={o=>!o&&setFollow(null)}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Set Promise / Follow-up Date</DialogTitle></DialogHeader>{follow&&<div className="space-y-3"><div className="rounded-lg bg-muted p-3"><p className="font-semibold">{follow.customer_name}</p><p className="text-xs text-muted-foreground">Balance {money(Number(follow.pending_amount))}</p></div><div><Label>Customer promised date *</Label><Input type="date" value={promiseDate} onChange={e=>setPromiseDate(e.target.value)}/></div><div><Label>Call note</Label><Textarea value={followNote} onChange={e=>setFollowNote(e.target.value)} placeholder="Customer said payment will be made on this date..."/></div></div>}<DialogFooter><Button variant="outline" onClick={()=>setFollow(null)}>Cancel</Button><Button onClick={schedule} disabled={saving||!promiseDate}>Set Reminder</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={!!receive} onOpenChange={o=>!o&&setReceive(null)}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Record Amount Received</DialogTitle></DialogHeader>{receive&&<div className="space-y-3"><p className="text-sm">{receive.customer_name} · Balance {money(Number(receive.pending_amount))}</p><div><Label>Amount received</Label><Input type="number" value={receiveAmount} onChange={e=>setReceiveAmount(e.target.value)}/></div></div>}<DialogFooter><Button variant="outline" onClick={()=>setReceive(null)}>Cancel</Button><Button onClick={recordReceived} disabled={saving}>Save Received</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
