// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated \u2014 connect this MCP server with your staff account." }],
    isError: true
  };
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the furniture catalog by name or product code and return pricing and stock details.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Product name or code to search for."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of products to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("products").select("id, product_code, product_name, material, dimensions, mrp, offer_price, stock_quantity, stock_status, reorder_level, is_published").is("deleted_at", null).or(`product_name.ilike.%${query}%,product_code.ilike.%${query}%`).order("product_name").limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/low-stock-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var low_stock_products_default = defineTool2({
  name: "low_stock_products",
  title: "Low stock products",
  description: "List catalog products whose stock quantity is at or below their reorder level.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(25).describe("Maximum number of products to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("products").select("id, product_code, product_name, stock_quantity, reorder_level, stock_status").is("deleted_at", null).order("stock_quantity").limit(500);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const low = (data ?? []).filter((p) => Number(p.stock_quantity ?? 0) <= Number(p.reorder_level ?? 0)).slice(0, limit ?? 25);
    return {
      content: [{ type: "text", text: JSON.stringify(low, null, 2) }],
      structuredContent: { products: low, count: low.length }
    };
  }
});

// src/lib/mcp/tools/list-quotations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_quotations_default = defineTool3({
  name: "list_quotations",
  title: "List quotations",
  description: "List recent quotations and orders, optionally filtered by pipeline stage, status, or customer name.",
  inputSchema: {
    stage: z3.number().int().min(1).max(6).optional().describe("Pipeline stage 1-6 to filter by."),
    status: z3.string().trim().min(1).optional().describe("Status filter, e.g. draft, finalized, delivered."),
    party: z3.string().trim().min(1).optional().describe("Customer/party name to search for."),
    limit: z3.number().int().min(1).max(50).default(20).describe("Maximum number of rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, status, party, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("quotations").select(
      "id, quotation_id, party_name, party_place, party_phone, status, pipeline_stage, document_type, lead_type, total, advance_amount, quotation_date, expected_delivery_date, created_at"
    ).is("deleted_at", null).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (stage) q = q.eq("pipeline_stage", stage);
    if (status) q = q.eq("status", status);
    if (party) q = q.ilike("party_name", `%${party}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { quotations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-quotation.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var get_quotation_default = defineTool4({
  name: "get_quotation",
  title: "Get quotation",
  description: "Fetch one quotation with its line items, using its human-readable quotation code (e.g. QT-1024).",
  inputSchema: {
    quotation_code: z4.string().trim().min(1).describe("The quotation code shown on the document.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ quotation_code }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: quotation, error } = await supabase.from("quotations").select("*").eq("quotation_id", quotation_code).is("deleted_at", null).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!quotation) {
      return { content: [{ type: "text", text: `No quotation found with code ${quotation_code}` }], isError: true };
    }
    const { data: items, error: itemsError } = await supabase.from("quotation_items").select("id, description, quantity, unit_price, amount, measurement, fulfillment_route, display_order").eq("quotation_id", quotation.id).order("display_order");
    if (itemsError) return { content: [{ type: "text", text: itemsError.message }], isError: true };
    const payload = { quotation, items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-open-enquiries.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_open_enquiries_default = defineTool5({
  name: "list_open_enquiries",
  title: "List open enquiries",
  description: "List unresolved customer complaints and service/repair requests from the enquiries inbox.",
  inputSchema: {
    kind: z5.enum(["all", "complaint", "service"]).default("all").describe("Which enquiry type to list."),
    limit: z5.number().int().min(1).max(50).default(20).describe("Maximum rows per type.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const want = kind ?? "all";
    const cap = limit ?? 20;
    const result = {};
    if (want === "all" || want === "complaint") {
      const { data, error } = await supabase.from("customer_complaints").select("id, complaint_code, customer_name, customer_phone, customer_place, issue_description, status, created_at").is("deleted_at", null).not("status", "in", "(resolved,closed,cancelled)").order("created_at", { ascending: false }).limit(cap);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.complaints = data ?? [];
    }
    if (want === "all" || want === "service") {
      const { data, error } = await supabase.from("customer_services").select("id, service_code, customer_name, customer_phone, customer_place, item_description, work_needed, estimated_cost, status, created_at").is("deleted_at", null).not("status", "in", "(resolved,closed,cancelled)").order("created_at", { ascending: false }).limit(cap);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.services = data ?? [];
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/resolve-enquiry.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var resolve_enquiry_default = defineTool6({
  name: "resolve_enquiry",
  title: "Mark enquiry resolved",
  description: "Mark a customer complaint or service request as resolved, using its complaint or service code.",
  inputSchema: {
    kind: z6.enum(["complaint", "service"]).describe("Whether the code belongs to a complaint or a service request."),
    code: z6.string().trim().min(1).describe("The complaint code or service code.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind, code }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const table = kind === "complaint" ? "customer_complaints" : "customer_services";
    const codeColumn = kind === "complaint" ? "complaint_code" : "service_code";
    const { data, error } = await supabase.from(table).update({ status: "resolved" }).eq(codeColumn, code).is("deleted_at", null).select("id, status");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: `No ${kind} found with code ${code}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `${kind} ${code} marked resolved.` }],
      structuredContent: { updated: data[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "https://thwleiywbpyccgtacczv.supabase.co".match(/https:\/\/([a-z0-9]+)\.supabase\.co/)?.[1] ?? "thwleiywbpyccgtacczv" ?? "project-ref-unset";
var mcp_default = defineMcp({
  name: "my-hitech",
  title: "My Hitech",
  version: "0.1.0",
  instructions: "Tools for My Hitech furniture operations. Use `search_products` and `low_stock_products` for the catalog and inventory, `list_quotations` and `get_quotation` for quotations and orders, and `list_open_enquiries` / `resolve_enquiry` for customer complaints and service requests. All tools act as the signed-in staff user and respect their permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_products_default,
    low_stock_products_default,
    list_quotations_default,
    get_quotation_default,
    list_open_enquiries_default,
    resolve_enquiry_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
