import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { AdminShell } from "@/components/admin/AdminShell";
import { OfficeStaffOnly } from "@/components/admin/OfficeStaffOnly";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "@/hooks/use-toast";
import { Loader2, AlertTriangle, HardHat, FileText, LifeBuoy, Wrench, CalendarClock, Clock3 } from "lucide-react";
import { isJobFinished } from "./AdminWorkerDetail";

type JobRow = { id:string; status:string; warehouse_status:string|null; job_type:string|null; is_urgent:boolean|null; worker_id:string|null; quotation_id:string|null; source_complaint_id:string|null; source_service_id:string|null; created_at:string; status_updated_at:string; due_at:string|null; last_worker_update_at:string|null; worker_update_note:string|null; worker_name:string|null; source_code:string|null; party_name:string|null; };
type ColumnKey = "assigned" | "in_progress" | "completed" | "dispatched";
const COLUMNS:{key:ColumnKey;label:string}[]=[{key:"assigned",label:"Assigned"},{key:"in_progress",label:"In Progress"},{key:"completed",label:"Completed"},{key:"dispatched",label:"Dispatched"}];
const columnFor=(j:JobRow):ColumnKey=>{if(j.warehouse_status==="dispatched")return"dispatched";if(isJobFinished(j.status))return"completed";if(j.status==="started"||j.status==="in_progress")return"in_progress";return"assigned"};
const timeAgo=(iso:string)=>{const s=Math.floor((Date.now()-new Date(iso).getTime())/1000);if(s<60)return`${s}s ago`;const m=Math.floor(s/60);if(m<60)return`${m}m ago`;const h=Math.floor(m/60);if(h<48)return`${h}h ago`;return`${Math.floor(h/24)}d ago`};
const jobTypeMeta=(t:string|null)=>{if(t==="complaint")return{label:"Complaint",icon:LifeBuoy,variant:"destructive" as const};if(t==="service")return{label:"Service",icon:Wrench,variant:"secondary" as const};return{label:"Production",icon:HardHat,variant:"outline" as const}};
const isOpenJob=(j:JobRow)=>!isJobFinished(j.status)&&j.warehouse_status!=="dispatched";
const isOverdue=(j:JobRow)=>!!j.due_at&&isOpenJob(j)&&new Date(j.due_at).getTime()<Date.now();
const lastActivityAt=(j:JobRow)=>j.last_worker_update_at||j.status_updated_at||j.created_at;
const needsFollowup=(j:JobRow)=>isOpenJob(j)&&Date.now()-new Date(lastActivityAt(j)).getTime()>24*60*60*1000;
const dateInputValue=(iso:string|null)=>iso?new Date(iso).toISOString().slice(0,10):"";

const Inner=()=>{
 const navigate=useNavigate(); const[jobs,setJobs]=useState<JobRow[]>([]),[loading,setLoading]=useState(true),[savingId,setSavingId]=useState<string|null>(null),[workerFilter,setWorkerFilter]=useState("all"),[urgentOnly,setUrgentOnly]=useState(false),[overdueOnly,setOverdueOnly]=useState(false),[search,setSearch]=useState("");
 const load=async()=>{setLoading(true);const{data,error}=await supabase.from("job_work_orders").select("id,status,warehouse_status,job_type,is_urgent,worker_id,quotation_id,source_complaint_id,source_service_id,created_at,status_updated_at,due_at,last_worker_update_at,worker_update_note").is("deleted_at",null).order("created_at",{ascending:false});if(error){toast({title:"Failed to load jobs",description:error.message,variant:"destructive"});setLoading(false);return}const rows=(data??[])as any[];const workerIds=Array.from(new Set(rows.map(r=>r.worker_id).filter(Boolean))),qIds=Array.from(new Set(rows.map(r=>r.quotation_id).filter(Boolean))),cIds=Array.from(new Set(rows.map(r=>r.source_complaint_id).filter(Boolean))),sIds=Array.from(new Set(rows.map(r=>r.source_service_id).filter(Boolean)));const[{data:ws},{data:qs},{data:cs},{data:ss}]=await Promise.all([workerIds.length?supabase.from("workers").select("id,name").in("id",workerIds):Promise.resolve({data:[]as any[]}),qIds.length?supabase.from("quotations").select("id,quotation_id,party_name").in("id",qIds):Promise.resolve({data:[]as any[]}),cIds.length?supabase.from("customer_complaints").select("id,complaint_code,customer_name").in("id",cIds):Promise.resolve({data:[]as any[]}),sIds.length?supabase.from("customer_services").select("id,service_code,customer_name").in("id",sIds):Promise.resolve({data:[]as any[]})]);const wMap=new Map((ws??[]).map((w:any)=>[w.id,w.name])),qMap=new Map((qs??[]).map((q:any)=>[q.id,q])),cMap=new Map((cs??[]).map((c:any)=>[c.id,c])),sMap=new Map((ss??[]).map((s:any)=>[s.id,s]));setJobs(rows.map(r=>{let source_code:string|null=null,party_name:string|null=null;if(r.source_complaint_id&&cMap.has(r.source_complaint_id)){const c:any=cMap.get(r.source_complaint_id);source_code=c.complaint_code;party_name=c.customer_name}else if(r.source_service_id&&sMap.has(r.source_service_id)){const s:any=sMap.get(r.source_service_id);source_code=s.service_code;party_name=s.customer_name}else if(r.quotation_id&&qMap.has(r.quotation_id)){const q:any=qMap.get(r.quotation_id);source_code=q.quotation_id;party_name=q.party_name}return{...r,worker_name:r.worker_id?(wMap.get(r.worker_id)??null):null,source_code,party_name}}));setLoading(false)};
 useEffect(()=>{load()},[]);
 const workers=useMemo(()=>{const m=new Map<string,string>();for(const j of jobs)if(j.worker_id&&j.worker_name)m.set(j.worker_id,j.worker_name);return Array.from(m.entries()).map(([id,name])=>({id,name})).sort((a,b)=>a.name.localeCompare(b.name))},[jobs]);
 const summary=useMemo(()=>({open:jobs.filter(isOpenJob).length,overdue:jobs.filter(isOverdue).length,followup:jobs.filter(needsFollowup).length,unassigned:jobs.filter(j=>isOpenJob(j)&&!j.worker_id).length}),[jobs]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return jobs.filter(j=>{if(workerFilter!=="all"&&j.worker_id!==workerFilter)return false;if(urgentOnly&&!j.is_urgent)return false;if(overdueOnly&&!isOverdue(j))return false;if(q&&!(j.source_code??"").toLowerCase().includes(q)&&!(j.party_name??"").toLowerCase().includes(q))return false;return true})},[jobs,workerFilter,urgentOnly,overdueOnly,search]);
 const byColumn=useMemo(()=>{const g:Record<ColumnKey,JobRow[]>={assigned:[],in_progress:[],completed:[],dispatched:[]};for(const j of filtered)g[columnFor(j)].push(j);return g},[filtered]);
 const moveTo=async(job:JobRow,target:ColumnKey)=>{if(columnFor(job)===target)return;setSavingId(job.id);const patch:{status:string;warehouse_status?:string;last_worker_update_at?:string}=target==="assigned"?{status:"assigned"}:target==="in_progress"?{status:"in_progress",last_worker_update_at:new Date().toISOString()}:target==="completed"?{status:"ready",warehouse_status:"in_warehouse",last_worker_update_at:new Date().toISOString()}:{status:"ready",warehouse_status:"dispatched"};const{error}=await supabase.from("job_work_orders").update(patch as any).eq("id",job.id);setSavingId(null);if(error){toast({title:"Update failed",description:error.message,variant:"destructive"});return}toast({title:"Status updated",description:`Moved to ${target.replace("_"," ")}`});setJobs(prev=>prev.map(j=>j.id===job.id?{...j,...patch,status_updated_at:new Date().toISOString()}:j))};
 const updateDueDate=async(job:JobRow,value:string)=>{setSavingId(job.id);const dueAt=value?new Date(`${value}T18:00:00+05:30`).toISOString():null;const{error}=await supabase.from("job_work_orders").update({due_at:dueAt}as any).eq("id",job.id);setSavingId(null);if(error){toast({title:"Due date update failed",description:error.message,variant:"destructive"});return}setJobs(prev=>prev.map(j=>j.id===job.id?{...j,due_at:dueAt}:j));toast({title:value?"Due date updated":"Due date cleared"})};
 const openJob=(j:JobRow)=>{if(j.source_complaint_id)navigate(`/admin/enquiries?open=complaint:${j.source_complaint_id}`);else if(j.source_service_id)navigate(`/admin/enquiries?open=service:${j.source_service_id}`);else if(j.quotation_id)navigate(`/admin/quotations/${j.quotation_id}`)};
 return <AdminShell><div className="space-y-4">
  <div className="admin-page-head flex items-start gap-3 p-4"><div className="admin-accent-tile admin-accent-rose flex h-10 w-10 shrink-0 items-center justify-center rounded-xl"><HardHat className="h-5 w-5"/></div><div><h1 className="font-display text-2xl md:text-3xl">Production Board</h1><p className="mt-1 text-sm text-muted-foreground">Worker jobs, deadlines and follow-up in one clear workflow.</p></div></div>
  <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Card className="p-3"><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Open Jobs</p><p className="mt-1 text-2xl font-semibold">{summary.open}</p></Card><Card className={summary.overdue?"border-destructive/20 bg-destructive/10 p-3":"p-3"}><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Overdue</p><p className="mt-1 text-2xl font-semibold">{summary.overdue}</p></Card><Card className={summary.followup?"border-amber-500/20 bg-amber-500/10 p-3":"p-3"}><p className="text-[10px] uppercase tracking-wide text-muted-foreground">No Update 24h+</p><p className="mt-1 text-2xl font-semibold">{summary.followup}</p></Card><Card className={summary.unassigned?"border-amber-500/20 bg-amber-500/10 p-3":"p-3"}><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Unassigned</p><p className="mt-1 text-2xl font-semibold">{summary.unassigned}</p></Card></div>
  <Card className="flex flex-wrap items-end gap-3 p-3"><div className="min-w-[180px] flex-1"><Label className="text-xs">Search</Label><Input placeholder="Quotation #, complaint/service code, customer…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="min-w-[180px]"><Label className="text-xs">Worker</Label><Select value={workerFilter} onValueChange={setWorkerFilter}><SelectTrigger><SelectValue placeholder="All workers"/></SelectTrigger><SelectContent><SelectItem value="all">All workers</SelectItem>{workers.map(w=><SelectItem key={w.id} value={w.id}>{w.name}</SelectItem>)}</SelectContent></Select></div><div className="flex items-center gap-2 pb-2"><Switch id="urgent" checked={urgentOnly} onCheckedChange={setUrgentOnly}/><Label htmlFor="urgent" className="cursor-pointer text-sm">Urgent only</Label></div><div className="flex items-center gap-2 pb-2"><Switch id="overdue" checked={overdueOnly} onCheckedChange={setOverdueOnly}/><Label htmlFor="overdue" className="cursor-pointer text-sm">Overdue only</Label></div></Card>
  {loading?<div className="flex justify-center py-12"><Loader2 className="h-6 w-6 animate-spin text-primary"/></div>:<div className="-mx-2 flex gap-3 overflow-x-auto px-2 pb-4 md:mx-0 md:px-0">{COLUMNS.map(col=>{const columnItems=byColumn[col.key];return <div key={col.key} className="w-[290px] shrink-0 md:w-[310px]"><div className="mb-2 flex items-center justify-between px-1"><h2 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{col.label}</h2><Badge variant="secondary">{columnItems.length}</Badge></div><div className="min-h-[120px] space-y-2 rounded-xl border bg-muted/30 p-2">{columnItems.length===0&&<p className="px-2 py-6 text-center text-xs text-muted-foreground">No jobs</p>}{columnItems.map(j=>{const meta=jobTypeMeta(j.job_type),Icon=meta.icon,overdue=isOverdue(j),followup=needsFollowup(j);return <Card key={j.id} className={`p-3 transition hover:shadow-md ${j.is_urgent||overdue?"border-destructive/20":followup?"border-amber-500/20":""}`}><button type="button" onClick={()=>openJob(j)} className="block w-full text-left"><div className="mb-1 flex flex-wrap items-center gap-1.5"><Badge variant={meta.variant} className="gap-1"><Icon className="h-3 w-3"/>{meta.label}</Badge>{j.is_urgent&&<Badge variant="destructive" className="gap-1"><AlertTriangle className="h-3 w-3"/>Urgent</Badge>}{overdue&&<Badge variant="destructive" className="gap-1"><CalendarClock className="h-3 w-3"/>Overdue</Badge>}{!overdue&&followup&&<Badge variant="outline" className="gap-1 border-amber-500/30 text-amber-700"><Clock3 className="h-3 w-3"/>Follow up</Badge>}</div><div className="flex items-center gap-1.5 text-sm font-medium"><FileText className="h-3.5 w-3.5 text-muted-foreground"/><span className="truncate">{j.source_code??"—"}</span></div>{j.party_name&&<p className="truncate text-xs text-muted-foreground">{j.party_name}</p>}<p className="mt-1 text-xs text-muted-foreground">{j.worker_name??"Unassigned"} · assigned {timeAgo(j.created_at)}</p>{isOpenJob(j)&&<p className={`mt-1 text-xs ${followup?"font-medium text-amber-700":"text-muted-foreground"}`}>Last activity: {timeAgo(lastActivityAt(j))}</p>}{j.worker_update_note&&<p className="mt-1 line-clamp-2 text-xs text-muted-foreground">Update: {j.worker_update_note}</p>}</button>{isOpenJob(j)&&<div className="mt-2 rounded-lg border bg-background/70 p-2"><Label className="text-[10px] uppercase tracking-wide text-muted-foreground">Production due date</Label><Input type="date" className={`mt-1 h-8 text-xs ${overdue?"border-destructive":""}`} value={dateInputValue(j.due_at)} onChange={e=>updateDueDate(j,e.target.value)} disabled={savingId===j.id}/></div>}<div className="mt-2"><Select value={columnFor(j)} onValueChange={v=>moveTo(j,v as ColumnKey)} disabled={savingId===j.id}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent>{COLUMNS.map(c=><SelectItem key={c.key} value={c.key}>{c.label}</SelectItem>)}</SelectContent></Select></div></Card>})}</div></div>})}</div>}
 </div></AdminShell>
};
const AdminProductionBoard=()=> <OfficeStaffOnly><Inner/></OfficeStaffOnly>;
export default AdminProductionBoard;