import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { AdminShell } from "@/components/admin/AdminShell";
import { OfficeStaffOnly } from "@/components/admin/OfficeStaffOnly";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
import { indiaDateKey } from "@/lib/deliveryPlanning";
import { leadCreatorLabel, leadSourceLabel } from "@/lib/leadSource";

type Lead = { id: string; lead_code: string; customer_name: string; customer_phone: string | null; customer_place: string | null; requirement: string | null; source: string; status: string; created_by: string | null; assigned_to: string | null; next_follow_up_at: string | null; follow_up_notes: string | null; created_at: string; converted_quotation_id: string | null; item_image_url: string | null };
type Staff = { user_id: string; display_name: string | null };
const selectClass = "h-10 rounded-md border bg-background px-2 text-sm";
const localInput = (iso: string | null) => { if (!iso) return ""; const d = new Date(iso); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}T${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`; };

function LeadsPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [params,setParams] = useSearchParams();
  const [rows, setRows] = useState<Lead[]>([]); const [staff, setStaff] = useState<Staff[]>([]); const [names, setNames] = useState<Record<string,string>>({});
  const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const [source,setSource]=useState("all"); const [status,setStatus]=useState("open"); const [owner,setOwner]=useState("all"); const [month,setMonth]=useState(""); const [search,setSearch]=useState(""); const [dueOnly,setDueOnly]=useState(false);
  const [edit,setEdit]=useState<Lead|null>(null); const [isNew,setIsNew]=useState(false); const [followDate,setFollowDate]=useState(""); const [confirmLead,setConfirmLead]=useState<Lead|null>(null);
  const load=async()=>{
    setLoading(true); setError("");
    try {
      const all: Lead[]=[];
      for(let offset=0;;offset+=500){const r=await (supabase as any).from("sales_leads").select("*").is("deleted_at",null).order("created_at",{ascending:false}).order("id").range(offset,offset+499);if(r.error)throw r.error;all.push(...r.data);if(r.data.length<500)break;}
      const [p,r]=await Promise.all([supabase.from("profiles").select("user_id,display_name"),supabase.from("user_roles").select("user_id,role").in("role",["admin","staff"])]);
      if(p.error||r.error)throw p.error||r.error;
      setNames(Object.fromEntries((p.data??[]).map(x=>[x.user_id,x.display_name||"Staff name unavailable"])));
      const eligible=new Set((r.data??[]).map(x=>x.user_id));setStaff((p.data??[]).filter(x=>eligible.has(x.user_id)));
      setRows(all);
    }catch(e:any){setError(e.message||"Could not load leads");}finally{setLoading(false);}
  };
  useEffect(()=>{void load();},[]);
  const openEdit=(lead:Lead)=>{setIsNew(false);setEdit({...lead});setFollowDate(localInput(lead.next_follow_up_at));};
  useEffect(()=>{const id=params.get("open");const row=rows.find(x=>x.id===id);if(row){openEdit(row);setParams({}, {replace:true});}},[params,rows]);
  const newLead=()=>{const id=crypto.randomUUID();setIsNew(true);setFollowDate("");setEdit({id,lead_code:`LD-${new Date().getFullYear()}-${id.slice(0,8).toUpperCase()}`,customer_name:"",customer_phone:"",customer_place:"",requirement:"",source:"manual",status:"pending",created_by:user?.id??null,assigned_to:user?.id??null,next_follow_up_at:null,follow_up_notes:"",created_at:new Date().toISOString(),converted_quotation_id:null,item_image_url:null});};
  const save=async()=>{
    if(!edit||busy)return;if(!edit.customer_name.trim())return toast.error("Enter customer name");
    setBusy(true);
    const fields={customer_name:edit.customer_name.trim(),customer_phone:edit.customer_phone||null,customer_place:edit.customer_place||null,requirement:edit.requirement||null,assigned_to:edit.assigned_to||null,next_follow_up_at:followDate?new Date(followDate).toISOString():null,follow_up_notes:edit.follow_up_notes||null,updated_at:new Date().toISOString()};
    let query=isNew?(supabase as any).from("sales_leads").insert({...fields,id:edit.id,lead_code:edit.lead_code,source:edit.source,created_by:user?.id,status:"pending"}):(supabase as any).from("sales_leads").update({...fields,...(!edit.converted_quotation_id?{status:edit.status}:{})}).eq("id",edit.id);
    if(!isNew&&!edit.converted_quotation_id)query=query.is("converted_quotation_id",null);
    const result=await query.select("id").single();setBusy(false);
    if(result.error)return toast.error(result.error.message);
    setEdit(null);toast.success(isNew?"Lead added":"Follow-up saved");void load();
  };
  const convert=async()=>{if(!confirmLead||busy)return;setBusy(true);const r=await(supabase as any).rpc("convert_sales_lead_to_quotation",{p_lead_id:confirmLead.id});setBusy(false);if(r.error||!r.data?.ok)return toast.error(r.error?.message||r.data?.error||"Conversion failed");navigate(`/admin/quotations/${r.data.quotation_id}`);};
  const periodRows=useMemo(()=>rows.filter(r=>!month||indiaDateKey(new Date(r.created_at)).startsWith(month)),[rows,month]);
  const visible=periodRows.filter(r=>(source==="all"||r.source===source)&&(status==="all"||(status==="open"?["pending","contacted"].includes(r.status):r.status===status))&&(owner==="all"||(owner==="unassigned"?!r.assigned_to:r.assigned_to===owner))&&(!dueOnly||(["pending","contacted"].includes(r.status)&&!!r.next_follow_up_at&&indiaDateKey(new Date(r.next_follow_up_at))<=indiaDateKey()))&&[r.lead_code,r.customer_name,r.customer_phone,r.customer_place].some(x=>String(x??"").toLowerCase().includes(search.toLowerCase())));
  return <AdminShell><div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-display text-2xl">Leads · enquiry follow-up</h1><p className="text-sm text-muted-foreground">ഓൺലൈൻ / മാനുവൽ enquiry → Sales follow-up → Quotation</p></div><Button onClick={newLead}>+ Add manual lead</Button></div>
    <details className="rounded-xl border bg-sky-50/40 p-3"><summary className="cursor-pointer font-semibold">സ്റ്റാഫ് എന്ത് ചെയ്യണം? · Workflow guide</summary><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm"><li><b>Lead:</b> Source, customer details പരിശോധിക്കുക; salesman, next follow-up/meeting സമയം രേഖപ്പെടുത്തുക.</li><li><b>Follow-up:</b> വിളിച്ച് ആവശ്യം, size, budget മനസ്സിലാക്കുക. Notes എഴുതുക; തയ്യാറാകാത്ത lead ഇവിടെ തുടരട്ടെ.</li><li><b>Quotation:</b> കസ്റ്റമർ quotation ആവശ്യപ്പെട്ട് മുന്നോട്ട് പോകാൻ സമ്മതിച്ചാൽ Convert ചെയ്യുക. Final price/order approval quotation-ൽ രേഖപ്പെടുത്തുക.</li><li><b>Items:</b> ഓരോ item-നും Ready stock / Customize നൽകുക. Custom item-ന് worker, due date; ലഭിച്ച സാധനം പരിശോധിക്കുക.</li><li><b>Delivery:</b> റെഡിയായ items തിരഞ്ഞെടുക്കുക → Delivery slip → PDF / Share PDF → WhatsApp. Balance മുഴുവൻ order-ന്റെ outstanding ആണ്.</li><li><b>Delivered:</b> ലഭിച്ച items മാത്രം tick ചെയ്യുക. ബാക്കിയുള്ളത് pending; payment/installation follow-up വേറെ.</li></ol></details>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[{label:"Total leads",key:"all",count:periodRows.length},{label:"Pending follow-up",key:"open",count:periodRows.filter(r=>["pending","contacted"].includes(r.status)).length},{label:"Converted",key:"converted",count:periodRows.filter(r=>r.status==="converted").length},{label:"Cancelled",key:"cancelled",count:periodRows.filter(r=>r.status==="cancelled").length}].map(c=><button key={c.key} onClick={()=>setStatus(c.key)} className="rounded-xl border bg-card p-3 text-left"><span className="text-xs">{c.label}</span><strong className="block text-2xl">{c.count}</strong></button>)}</div>
    <div className="flex flex-wrap gap-2"><Input className="sm:w-52" aria-label="Search leads" placeholder="Name / phone / lead code" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Lead source" className={selectClass} value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option>{["website","manual","whatsapp","other"].map(s=><option key={s} value={s}>{leadSourceLabel(s)} ({periodRows.filter(r=>r.source===s).length})</option>)}</select><select aria-label="Lead status" className={selectClass} value={status} onChange={e=>setStatus(e.target.value)}>{["open","all","pending","contacted","converted","lost","cancelled"].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Salesman" className={selectClass} value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">All salesmen</option><option value="unassigned">Not assigned</option>{staff.map(s=><option key={s.user_id} value={s.user_id}>{s.display_name||"Staff"}</option>)}</select><Input className="w-44" type="month" aria-label="Created month" value={month} onChange={e=>setMonth(e.target.value)}/><Button variant={dueOnly?"default":"outline"} onClick={()=>setDueOnly(!dueOnly)}>Today / overdue follow-up</Button><Button variant="ghost" onClick={()=>{setSource("all");setStatus("all");setOwner("all");setMonth("");setDueOnly(false);setSearch("");}}>Clear filters</Button></div>
    {error&&<div role="alert" className="rounded-lg border border-red-300 p-3">{error}<Button variant="outline" onClick={load}>Retry</Button></div>}
    {loading?<p>Loading leads…</p>:<><p className="text-xs text-muted-foreground">{visible.length} leads shown</p><div className="grid gap-3 lg:grid-cols-2">{visible.map(r=><div key={r.id} className="space-y-3 rounded-xl border-2 bg-card p-4"><div className="flex flex-wrap gap-2"><Badge>{leadSourceLabel(r.source)}</Badge><Badge variant="outline">{r.status}</Badge><span className="text-xs">{r.lead_code}</span></div><h2 className="font-semibold">{r.customer_name} · {r.customer_place}</h2><p className="text-sm">{r.customer_phone}</p><div className="grid gap-1 text-xs"><p><b>Entered by:</b> {leadCreatorLabel(r.source,r.created_by,names)}</p><p><b>Follow-up salesman:</b> {r.assigned_to?names[r.assigned_to]||"Staff name unavailable":"Not assigned"}</p><p><b>Next call / meeting:</b> {r.next_follow_up_at?new Date(r.next_follow_up_at).toLocaleString("en-IN"):"Not scheduled"}</p></div><p className="line-clamp-3 text-sm text-muted-foreground">{r.requirement}</p><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>openEdit(r)}>Open / Follow-up</Button>{r.customer_phone&&<Button asChild variant="outline" size="sm"><a href={`tel:${r.customer_phone}`}>Call</a></Button>}{r.converted_quotation_id?<Button asChild size="sm"><Link to={`/admin/quotations/${r.converted_quotation_id}`}>Open quotation</Link></Button>:["pending","contacted"].includes(r.status)&&<Button size="sm" onClick={()=>setConfirmLead(r)}>Convert to quotation</Button>}</div></div>)}</div>{!visible.length&&!error&&<p>No leads match these filters.</p>}</>}
  </div>
  <Dialog open={!!edit} onOpenChange={o=>!o&&!busy&&setEdit(null)}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{isNew?"Add manual lead":"Lead details & follow-up"}</DialogTitle></DialogHeader>{edit&&<div className="space-y-3"><p className="text-sm">{leadSourceLabel(edit.source)} · Entered by: {leadCreatorLabel(edit.source,edit.created_by,names)}</p>{isNew&&<label className="block text-sm">Source<select className={`${selectClass} ml-2`} value={edit.source} onChange={e=>setEdit({...edit,source:e.target.value})}><option value="manual">Manual / walk-in / phone</option><option value="whatsapp">WhatsApp</option><option value="other">Other</option></select></label>}{([['customer_name','Customer name'],['customer_phone','Phone'],['customer_place','Place']] as const).map(([key,label])=><label key={key} className="block text-sm">{label}<Input value={edit[key]??""} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}<label className="block text-sm">Requirement / requested items<Textarea value={edit.requirement??""} onChange={e=>setEdit({...edit,requirement:e.target.value})}/></label>{edit.item_image_url&&<img src={edit.item_image_url} alt="Customer reference" className="max-h-44 rounded-lg object-contain"/>}<label className="block text-sm">Follow-up salesman<select className={`${selectClass} w-full`} value={edit.assigned_to??""} onChange={e=>setEdit({...edit,assigned_to:e.target.value||null})}><option value="">Not assigned</option>{staff.map(s=><option key={s.user_id} value={s.user_id}>{s.display_name||"Staff"}</option>)}</select></label><label className="block text-sm">Next call / meeting<Input type="datetime-local" value={followDate} onChange={e=>setFollowDate(e.target.value)}/></label><label className="block text-sm">Follow-up / meeting notes<Textarea value={edit.follow_up_notes??""} onChange={e=>setEdit({...edit,follow_up_notes:e.target.value})}/></label>{!isNew&&!edit.converted_quotation_id&&<label className="block text-sm">Status<select className={`${selectClass} w-full`} value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{["pending","contacted","lost","cancelled"].map(s=><option key={s}>{s}</option>)}</select></label>}<Button disabled={busy} onClick={save} className="w-full">{busy?"Saving…":"Save lead / follow-up"}</Button>{edit.converted_quotation_id&&<Button asChild variant="outline" className="w-full"><Link to={`/admin/quotations/${edit.converted_quotation_id}`}>Open linked quotation</Link></Button>}</div>}</DialogContent></Dialog>
  <Dialog open={!!confirmLead} onOpenChange={o=>!o&&!busy&&setConfirmLead(null)}><DialogContent><DialogHeader><DialogTitle>Create quotation for {confirmLead?.customer_name}?</DialogTitle></DialogHeader><p className="text-sm">കസ്റ്റമറുമായി സംസാരിച്ചു quotation തയ്യാറാക്കാൻ സമ്മതം ലഭിച്ചോ? Source, entered-by, salesman വിവരങ്ങൾ linked lead-ൽ നിലനിൽക്കും. Final order confirmation quotation-ൽ രേഖപ്പെടുത്തണം.</p><Button disabled={busy} onClick={convert}>{busy?"Opening…":"Customer agreed · Create quotation"}</Button></DialogContent></Dialog>
  </AdminShell>;
}
export default function AdminLeads(){return <OfficeStaffOnly><LeadsPage/></OfficeStaffOnly>;}
