import {it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
const state=vi.hoisted(()=>({production:0,delivery:0}));
vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({isAdmin:true,isOfficeStaff:true,isWarehouse:false,isDelivery:false,isMeasurementStaff:false,user:{id:'a'},loading:false})}));
vi.mock('@/components/admin/AdminShell',()=>({AdminShell:({children}:any)=>children}));
vi.mock('@/components/admin/CommandCenterPanel',()=>({CommandCenterPanel:()=>null}));
vi.mock('@/components/admin/ReceivablesTodayPanel',()=>({ReceivablesTodayPanel:()=>null}));
vi.mock('@/components/admin/SalesFollowupPanel',()=>({SalesFollowupPanel:()=>null}));
vi.mock('./AdminProductionAnalyticsDashboard',async()=>{const React=await import('react');return {default:()=>{React.useEffect(()=>{state.production++;},[]);return <p>Production loaded data</p>;}};});
vi.mock('./AdminDeliveryAnalyticsDashboard',async()=>{const React=await import('react');return {default:()=>{React.useEffect(()=>{state.delivery++;},[]);return <p>Delivery loaded data</p>;}};});
import AdminOverview from './AdminOverview';
it('loads only selected departments and keeps their data on return',async()=>{
 render(<AdminOverview/>);
 expect(state.production).toBe(0);expect(state.delivery).toBe(0);
 fireEvent.mouseDown(screen.getByRole('tab',{name:'Production'}),{button:0,ctrlKey:false});
 await screen.findByText('Production loaded data');
 expect(state.production).toBe(1);
 fireEvent.mouseDown(screen.getByRole('tab',{name:'Delivery'}),{button:0,ctrlKey:false});
 await screen.findByText('Delivery loaded data');
 expect(screen.getByText('Production loaded data').closest('[role="tabpanel"]')).toHaveAttribute('hidden');
 fireEvent.mouseDown(screen.getByRole('tab',{name:'Production'}),{button:0,ctrlKey:false});
 await waitFor(()=>expect(screen.getByText('Production loaded data').closest('[role="tabpanel"]')).not.toHaveAttribute('hidden'));
 expect(state.production).toBe(1);
 expect(state.delivery).toBe(1);
});
